### ISSUE TITLE
Implement the ability to stop audio

### ISSUE THREAD

**Issue by Zealls** [BEANSQUAD/paul-bot#8]
Without having to abuse an 'unintended feature'

**Comment by elsueter** [comment]
See lines : 40-50, 97-115 in "media.go".
Disconnect function -> does what it says and disconnects the bot from its current channel
Stop checks if the player is currently playing and then stops the encoding session from running, it then disconnects from the channel which will clear its current streaming session buffer before it joins again when requested to play a different audio stream.

Also reduced the streaming session buffer to a minimal number of frames so that the buffer after stopping the encoding session will not be huge
